# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b78bea886eceaae70b103441c35dd34ba49a97c69c2c3439b6d6fb68ca307483e255d982c9ce27015eff76bdb12d33c58192b229f9e975cf3d9075f4f582b3f8

test:
  secret_key_base: 6fa6caf687bd4dd618078e11128b4d1edc7c082964ad1d320e3c448cf4877a9928045d9cd079382a26f296cbf54ac8af7368e12e907b05006c880b5c6c4ab5df

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
